# Generated by Django 3.2.8 on 2022-04-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_service',
            name='value',
            field=models.FloatField(),
        ),
    ]
