# Generated by Django 3.2.8 on 2022-04-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_alter_type_service_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100, verbose_name='Manzil')),
                ('x_r', models.CharField(max_length=90, verbose_name='X/R')),
                ('sh_x', models.CharField(max_length=90, verbose_name='Sh.X')),
                ('bank', models.CharField(max_length=1000, verbose_name='Toshkent shaxar Markaziybank')),
                ('mfo', models.CharField(max_length=50, verbose_name='MFO')),
                ('oked', models.CharField(max_length=500, verbose_name='OKED')),
                ('inn', models.CharField(max_length=15, verbose_name='INN')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Telefon')),
            ],
        ),
        migrations.DeleteModel(
            name='agreemant',
        ),
    ]
